default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: shazam_cable_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: shazam_cable_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: shazam_cable_production
  pool: 5
  timeout: 5000
